export const AuditEvents = {
  GAP_CHECK_RUN: 'GAP_CHECK_RUN',
  AUDIT_SUMMARY_RUN: 'AUDIT_SUMMARY_RUN',
  ANOMALY_DETECT_RUN: 'ANOMALY_DETECT_RUN',
  REMEDIATION_CREATED: 'REMEDIATION_CREATED',
  REMEDIATION_RESOLVED: 'REMEDIATION_RESOLVED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  DOCUMENT_CHAT: 'DOCUMENT_CHAT',
} as const;

export type AuditEvent = (typeof AuditEvents)[keyof typeof AuditEvents];