import puppeteer from 'puppeteer';
import type { EvidencePackage } from './documents.types';

export async function renderEvidencePackagePdf(pkg: EvidencePackage): Promise<Buffer> {
  const html = generateHtml(pkg);

  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
      format: 'A4',
      margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' },
      printBackground: true,
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

function generateHtml(pkg: EvidencePackage): string {
  const auditSummary = pkg.document.auditSummary as any;
  const anomalyReport = pkg.document.anomalyReport;
  const remediations = pkg.remediations.items;
  const { frameworks, gapsByFramework } = pkg.complianceSummary;

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Arial, sans-serif; color: #1E2F5C; font-size: 11px; line-height: 1.5; }
  .header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #D4A017; padding-bottom: 16px; }
  .header h1 { font-size: 22px; margin: 0; color: #1E2F5C; }
  .header h2 { font-size: 14px; margin: 4px 0; color: #5A6A85; font-weight: normal; }
  .header .meta { font-size: 10px; color: #5A6A85; margin-top: 8px; }
  .section { margin-bottom: 20px; }
  .section-title { font-size: 13px; font-weight: bold; color: #1E2F5C; border-bottom: 1px solid #D4A017; padding-bottom: 4px; margin-bottom: 10px; }
  .field { margin-bottom: 4px; }
  .label { font-weight: bold; color: #5A6A85; }
  .badge { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 9px; font-weight: bold; margin-right: 4px; }
  .badge-critical { background: #fee2e2; color: #991b1b; }
  .badge-high { background: #fef3c7; color: #92400e; }
  .badge-warning { background: #fef3c7; color: #92400e; }
  .badge-medium { background: #dbeafe; color: #1e40af; }
  .badge-info { background: #dbeafe; color: #1e40af; }
  .badge-low { background: #f0fdf4; color: #166534; }
  .badge-open { background: #fee2e2; color: #991b1b; }
  .badge-resolved { background: #dcfce7; color: #166534; }
  .badge-in_progress { background: #fef3c7; color: #92400e; }
  .badge-success { background: #dcfce7; color: #166534; }
  .badge-error { background: #fee2e2; color: #991b1b; }
  table { width: 100%; border-collapse: collapse; font-size: 10px; }
  th { background: #1E2F5C; color: white; padding: 6px 8px; text-align: left; }
  td { padding: 5px 8px; border-bottom: 0.5px solid #DEE2E8; }
  tr:nth-child(even) { background: #F8F9FA; }
  .footer { margin-top: 32px; border-top: 1px solid #DEE2E8; padding-top: 8px; font-size: 9px; color: #5A6A85; text-align: center; }
  .watermark { color: #D4A017; font-weight: bold; }
</style>
</head>
<body>

<div class="header">
  <h1>PACTURA.AI</h1>
  <h2>Compliance Evidence Package</h2>
  <div class="meta">
    Generated: ${new Date().toLocaleString()} &nbsp;|&nbsp;
    Organization: ${pkg.orgId} &nbsp;|&nbsp;
    Generated by: ${pkg.generatedBy}
  </div>
</div>

<div class="section">
  <div class="section-title">Document Information</div>
  <div class="field"><span class="label">Name:</span> ${pkg.document.name}</div>
  <div class="field"><span class="label">Type:</span> ${pkg.document.fileType}</div>
  <div class="field"><span class="label">Version:</span> v${pkg.document.version}</div>
  <div class="field"><span class="label">Status:</span> ${pkg.document.status}</div>
  <div class="field"><span class="label">Uploaded by:</span> ${pkg.document.uploadedBy}</div>
</div>

${auditSummary ? `
<div class="section">
  <div class="section-title">AI Analysis Summary</div>
  <div class="field"><span class="label">Contract Type:</span> ${auditSummary.contractType ?? 'N/A'}</div>
  ${auditSummary.effectiveDate ? `<div class="field"><span class="label">Effective Date:</span> ${auditSummary.effectiveDate}</div>` : ''}
  ${auditSummary.termLength ? `<div class="field"><span class="label">Term Length:</span> ${auditSummary.termLength}</div>` : ''}
  ${auditSummary.totalValue ? `<div class="field"><span class="label">Total Value:</span> ${auditSummary.totalValue}</div>` : ''}
  <div class="field"><span class="label">Key Parties:</span> ${(auditSummary.keyParties ?? []).join(', ') || 'N/A'}</div>
  <div class="field"><span class="label">Summary:</span> ${auditSummary.summary ?? 'N/A'}</div>
  ${(auditSummary.keyObligations ?? []).length > 0 ? `
  <div class="field" style="margin-top:8px;"><span class="label">Key Obligations:</span>
    <ul style="margin:4px 0 0 16px; padding:0;">
      ${(auditSummary.keyObligations as string[]).map((o) => `<li>${o}</li>`).join('')}
    </ul>
  </div>` : ''}
  ${(auditSummary.complianceFlags ?? []).length > 0 ? `
  <div class="field" style="margin-top:8px;"><span class="label">Compliance Flags:</span></div>
  ${(auditSummary.complianceFlags as { severity: string; label: string }[]).map((f) => `
    <div>&nbsp;&nbsp;<span class="badge badge-${f.severity}">${f.severity.toUpperCase()}</span> ${f.label}</div>
  `).join('')}` : ''}
</div>
` : ''}

${frameworks.length > 0 ? `
<div class="section">
  <div class="section-title">Compliance Gap Analysis</div>
  <div class="field" style="margin-bottom:8px;">
    Total unmet requirements: ${pkg.complianceSummary.totalGaps} across ${frameworks.length} framework(s)
  </div>
  <table>
    <tr>
      <th>Framework</th>
      <th>Unmet</th>
      <th>Missing</th>
      <th>Partial</th>
      <th>Met</th>
    </tr>
    ${frameworks.map((fw) => {
      const s = gapsByFramework[fw];
      const rawGaps = pkg.document.complianceGaps?.[fw]?.gaps ?? [];
      const metCount = rawGaps.filter((g) => g.status === 'met').length;
      return `
    <tr>
      <td>${fw}</td>
      <td>${s.total}</td>
      <td>${s.missing}</td>
      <td>${s.partial}</td>
      <td>${metCount}</td>
    </tr>`;
    }).join('')}
  </table>
</div>
` : ''}

${anomalyReport ? `
<div class="section">
  <div class="section-title">Anomaly Detection Report</div>
  <div class="field"><span class="label">Document Type:</span> ${anomalyReport.documentType}</div>
  <div class="field"><span class="label">Total Anomalies:</span> ${anomalyReport.totalAnomalies}
    (Critical: ${anomalyReport.criticalCount}, High: ${anomalyReport.highCount},
    Medium: ${anomalyReport.mediumCount}, Low: ${anomalyReport.lowCount})
  </div>
  ${anomalyReport.anomalies.length > 0 ? `
  <table style="margin-top:8px;">
    <tr><th>Severity</th><th>Title</th><th>Description</th></tr>
    ${anomalyReport.anomalies.map((a) => `
    <tr>
      <td><span class="badge badge-${a.severity}">${a.severity.toUpperCase()}</span></td>
      <td>${a.title}</td>
      <td>${a.description}</td>
    </tr>`).join('')}
  </table>` : ''}
</div>
` : ''}

${remediations.length > 0 ? `
<div class="section">
  <div class="section-title">Remediation Tasks</div>
  <div class="field" style="margin-bottom:8px;">
    Total: ${pkg.remediations.total} &nbsp;|&nbsp;
    Open: ${pkg.remediations.open} &nbsp;|&nbsp;
    In Progress: ${pkg.remediations.inProgress} &nbsp;|&nbsp;
    Resolved: ${pkg.remediations.resolved}
  </div>
  <table>
    <tr><th>Status</th><th>Severity</th><th>Title</th><th>Framework</th><th>Due Date</th><th>Assignee</th></tr>
    ${remediations.map((r) => `
    <tr>
      <td><span class="badge badge-${r.status}">${r.status.toUpperCase()}</span></td>
      <td><span class="badge badge-${r.severity}">${r.severity.toUpperCase()}</span></td>
      <td>${r.title}</td>
      <td>${r.framework}</td>
      <td>${r.dueDate ?? 'Not set'}</td>
      <td>${r.assigneeEmail ?? 'Unassigned'}</td>
    </tr>`).join('')}
  </table>
</div>
` : ''}

<div class="section">
  <div class="section-title">Immutable Audit Trail</div>
  <table>
    <tr><th>Timestamp</th><th>Action</th><th>Model</th><th>Tokens</th><th>Status</th></tr>
    ${pkg.auditTrail.length === 0
      ? `<tr><td colspan="5" style="text-align:center; color:#5A6A85;">No audit events recorded</td></tr>`
      : (pkg.auditTrail as any[]).map((e) => {
          const ts = e.timestamp?._seconds
            ? new Date(e.timestamp._seconds * 1000).toLocaleString()
            : 'Unknown';
          return `
    <tr>
      <td>${ts}</td>
      <td>${e.action ?? '—'}</td>
      <td>${e.modelUsed ?? 'N/A'}</td>
      <td>${e.tokensUsed ?? 0}</td>
      <td><span class="badge badge-${e.responseStatus}">${e.responseStatus ?? 'N/A'}</span></td>
    </tr>`;
        }).join('')}
  </table>
</div>

<div class="footer">
  <span class="watermark">PACTURA.AI</span> — Audit-Ready Compliance Intelligence &nbsp;|&nbsp;
  Document ID: ${pkg.documentId} &nbsp;|&nbsp;
  ${new Date().toISOString()}
</div>

</body>
</html>`;
}
